name: Publish package on NPM & GPR
on:
  push:
    branches:
      - production

jobs:
  build:
    name: Package build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15

      - run: npm install -g yarn
      - run: yarn ci
      - run: yarn lint:prod
      # - run: yarn test
      - run: yarn build
      - run: yarn pack
      - shell: bash
        run: |
          PACKAGE_VERSION=`node -e "console.log(require('./package.json').version);"`
          PACKAGE_NAME="byloth-html-element-style-v${PACKAGE_VERSION}.tgz"
          tar -xzvf "${PACKAGE_NAME}" -C "."

      - uses: actions/upload-artifact@v2
        with:
          name: byloth-html-element-style
          path: package

  #
  # test:
  #   name: Package test
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - [...]
  #

  npm-publish:
    name: Publish on NPM
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/

      - run: npm install -g yarn
      - uses: actions/download-artifact@v2
        with:
          name: byloth-html-element-style

      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  gpr-publish:
    name: Publish on GPR
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com/

      - run: npm install -g yarn
      - uses: actions/download-artifact@v2
        with:
          name: byloth-html-element-style

      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
